//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Network
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int id { get; set; }
        public int id_user { get; set; }
        public System.DateTime time { get; set; }
        public bool watched { get; set; }
        public Nullable<System.DateTime> watch_time { get; set; }
        public int type_notification { get; set; }
    }
}
