//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Network
{
    using System;
    using System.Collections.Generic;
    
    public partial class People
    {
        public int id { get; set; }
        public string urlid { get; set; }
        public System.DateTime date_registration { get; set; }
        public int community { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public Nullable<bool> gender { get; set; }
        public System.DateTime date_birth { get; set; }
        public string email { get; set; }
        public bool confirm_email { get; set; }
        public string password { get; set; }
        public string mobile_phone { get; set; }
        public bool deleted { get; set; }
        public Nullable<System.DateTime> date_delete { get; set; }
        public Nullable<int> native_town { get; set; }
        public Nullable<int> town { get; set; }
        public string skype { get; set; }
        public string instagram { get; set; }
        public string twitter { get; set; }
        public string vkontakte { get; set; }
        public string status { get; set; }
        public string avatars { get; set; }
        public string languages { get; set; }
        public Nullable<int> faculty { get; set; }
        public Nullable<int> period_study { get; set; }
        public Nullable<int> chair { get; set; }
        public Nullable<int> form_study { get; set; }
        public Nullable<int> student_status { get; set; }
    
        public virtual Community Community1 { get; set; }
        public virtual Gender Gender1 { get; set; }
    }
}
