//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Network
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int id { get; set; }
        public string urlid { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public System.DateTime dateOfBirth { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string mobilePhone { get; set; }
        public string gender { get; set; }
        public string country { get; set; }
        public string town { get; set; }
        public string state { get; set; }
        public string Expr1 { get; set; }
    }
}
