//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Network
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public int id { get; set; }
        public int id_owner { get; set; }
        public string start_name { get; set; }
        public string current_name { get; set; }
        public string url { get; set; }
        public Nullable<bool> have_miniature { get; set; }
        public System.DateTime date_upload { get; set; }
        public bool deleted { get; set; }
        public Nullable<System.DateTime> date_delete { get; set; }
    }
}
